### ISSUE TITLE
[slider]

### ISSUE THREAD

**Issue by hchaase** [kookma/Tiddlyshow#1]
This is a comment on the slider plugin, but could not find a repo for it. Thought tiddly show might be related. Sorry

If you use the **seamless** theme, the navigation bar covers the button of the tiddler. And if you use a custom style sheet, the navigation bar will also cover that content

![billede](https://user-images.githubusercontent.com/2864323/72964541-80a91f00-3dba-11ea-96ca-11cc7cb37099.png)

**Comment by hchaase** [comment]
Is this a problem with the seamless theme or your plugin?? I don't know

**Comment by kookma** [comment]
@hchaase 
Use this https://github.com/kookma/slider repo

By the way Unfortunately TW does not follow a standard rule to implement its styles so one has to check new plugins with all those themes, ...

I confirm there is a conflict, I will return to this latter to address this issue!
Feel free to hack the slider CSS.

**Comment by hchaase** [comment]
ups.. I only looked at the overview tab. my bad. 

I look a little at the css, but with my limited coding knowledge I could not fix it in the slider css
